<?
/**
 * \Barranco\Checkout
 * 
 * @var \Barranco\Checkout\Block\Onepage $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<div id="my-checkout" data-bind="scope:'my-checkout'" class="my-checkout-container">
    <div id="my-checkout-loader" data-role="my-checkout-loader" class="loading-mask" data-mage-init='{"myCheckoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $escaper->escapeHtmlAttr(__('Loading...')) ?>">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#my-checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
</div>
